### PR TITLE
KHR_materials_unlit Support

### PR DESCRIPTION
**Pull request by MackeyK24**
Support for unlit materials

Fixes #

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by willeastcott** [comment]
Have you tested this against any glTF 2.0 models? I'm wondering if this PR treats baseColorFactor correctly. Shouldn't that be set on the material's emissive property if the material is unlit?

**Comment by MackeyK24** [comment]
Just disables the lighting... no need change base color. 

Note: this is also how BabylonJs GLTF parser handles the KHR unlit flag

**Comment by willeastcott** [comment]
Hey @cx20, do you have any glTF assets that use this extension that can test conformance?

**Comment by MackeyK24** [comment]
Yo @willeastcott ... I dont think youy really need to do all that. According to the spec.. Just the presence of "KHR_materials_unlit" extension is all that is needed... That tells the implementation NOT to apply traditional lighting to the PBR material... Just use the texture colors as is... dont try to "Light" or "Underlight" areas on the model just because the light is hitting at a certern angle... The matertial setup is the exact same...

BabylonJS... simply looks for the presence of the "KHR_materials_unlit" and if it exists it simply sets the material.unlit = true

In PlayCanvas we should just say material.useLighting = false.

I did an example convert from GLTF using the converter listed by @cx20 ... And checked the convet to unlit check box... It simply adds the Unlit json to each material... Here is the output from that convert:

```
    "materials": [
        {
            "pbrMetallicRoughness": {
                "baseColorFactor": [
                    0.904661357,
                    0.0822827,
                    0.005605389,
                    1
                ],
                "metallicRoughnessTexture": {
                    "index": 1
                }
            },
            "normalTexture": {
                "index": 0
            },
            "emissiveFactor": [
                0.5600193,
                0.0390281938,
                0
            ],
            "name": "mat_01",
            "extras": {
                "metadata": {
                    "glossyreflections": true,
                    "specularhighlights": true
                }
            },
            "extensions": {
                "KHR_materials_unlit": {}
            }
        },
        {
            "pbrMetallicRoughness": {
                "baseColorFactor": [
                    0.4910209,
                    0.89626956,
                    0.8069525,
                    1
                ],
                "metallicFactor": 0.0002817641361616552,
                "roughnessFactor": 0.5
            },
            "normalTexture": {
                "index": 2
            },
            "occlusionTexture": {
                "index": 3
            },
            "name": "mat_02",
            "extras": {
                "metadata": {
                    "glossyreflections": true,
                    "specularhighlights": true
                }
            },
            "extensions": {
                "KHR_materials_unlit": {}
            }
        }
    ],
```

So my little PR should be perfect :)

**Comment by willeastcott** [comment]
Fair enough! 😄

**Pull request merged**
